site_name: Spylib
site_url: https://example.com/
repo_url: https://github.com/SatelCreative/satel-spylib
theme:
  name: material
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - ...
  - Development - Contributing: development-contributing.md
plugins:
  - search
  - awesome-pages
markdown_extensions:
- pymdownx.superfences
