[tool.poetry]
name = "satel-shopify"
version = "0.1.0"
description = "A library to facilitate interfacing with Shopify's API"
authors = ["Anthony Hillairet <ant@ßatel.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.1"
httpx = "^0.18.1"
loguru = "^0.5.3"
tenacity = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
mypy = "^0.812"
mypy-extensions = "^0.4.3"
flake8 = "^3.9.2"
flake8-isort = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_third_party = ["fastapi", "pydantic", "starlette"]
